<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Regression1"
           tests="2"
           failures="2"
           errors="0"
           skipped="0"
           time="0.000">
  <properties />
            <testcase name="setUp" time="0.000" classname="com.catalog.common.common">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:178)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:277)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
      </failure>

          </testcase>
            <testcase name="tearDown" time="0.000" classname="com.catalog.common.common">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:178)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:308)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
